inputSet:
  name: Build_jainrosh_awesome_compose_1721841018198-push-trigger-input-set
  identifier: Build_jainrosh_awesome_compose_1721841018198pushtriggerinputset
  orgIdentifier: default
  projectIdentifier: default_project
  pipeline:
    identifier: Build_jainrosh_awesome_compose_1721841018198
    properties:
      ci:
        codebase:
          build:
            type: branch
            spec:
              branch: <+trigger.branch>
